### PR TITLE
Make dce installable as Ruby gem

### PR DESCRIPTION
**Pull request by kasperg**
I thought it would be nice to have dce work as a Ruby gem. This makes it even easier to install and update.

This PR adds an initial gemspec. Ther `dce` script has to be located in `bin` folder to work
as an executable so I moved it there.

Note that this is my first attempt at creating a Ruby gem. It is basicly the result of going through [a tutorial](http://guides.rubygems.org/make-your-own-gem/). I have not published it anywhere.

I tested the change by:

1. Building the gem locally on a machine where `dce` has not been used before
2. Installing the locally build gem
3. Running `dce`

### CODE REVIEW

**Comment by xendk** [comment]
Fixed the tests: https://github.com/xendk/dce/tree/gem

So, how would one go about installing the gem?

**Comment by kasperg** [comment]
:+1:

Once it is published it should be as simple as `gem install dce`.

**Comment by xendk** [comment]
Published... Where?

**Comment by kasperg** [comment]
[RubyGems.org](http://rubygems.org)

The tutorial provided these instructions:

> Now you can share hola with the rest of the Ruby community. Publishing your gem out to RubyGems.org only takes one command, provided that you have an account on the site. To setup your computer with your RubyGems account:

```
$ curl -u qrush https://rubygems.org/api/v1/api_key.yaml >
~/.gem/credentials; chmod 0600 ~/.gem/credentials

Enter host password for user 'qrush':
```

> If you’re having problems with curl, OpenSSL, or certificates, you might want to simply try entering the above URL in your browser’s address bar. Your browser will ask you to login to RubyGems.org. Enter your username and password. Your browser will now try to download the file api_key.yaml. Save it in ~/.gem and call it ‘credentials’

> Once this has been setup, you can push out the gem:

```
% gem push hola-0.0.0.gem
Pushing gem to RubyGems.org...
Successfully registered gem: hola (0.0.0)
```

**Comment by arnested** [comment]
If Homebrew do:

* New repo `xendk/homebrew-dce`
* Repo has a folder `Formula` with a file `dce.rb`:
```ruby
class Dce < Formula
  desc "Run shell commands in docker"
  homepage "https://github.com/xendk/dce"
  head "https://github.com/xendk/dce.git"

  bottle :unneeded

  depends_on :ruby => "1.9"

  def install
    bin.install "dce"
  end

  test do
    system "#{bin}/dce", "--help"
  end
end

```

User do `brew tap xendk/dce; brew install --HEAD`.

Ideally you should tag releases of DCE. Then a release can be added to the formula and people can avoid the `--HEAD` option and get updates once they are published (and they do a `brew upgrade`).

With a release the `dce.rb` would look like:
```ruby
class Dce < Formula
  desc "Run shell commands in docker"
  homepage "https://github.com/xendk/dce"
  url "https://github.com/xendk/dce/archive/v1.0.0.tar.gz"
  sha256 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  head "https://github.com/xendk/dce.git"

  bottle :unneeded

  depends_on :ruby => "1.9"

  def install
    bin.install "dce"
  end

  test do
    system "#{bin}/dce", "--help"
  end
end
```

**Comment by kasperg** [comment]
🎉

**Pull request merged**
