### PR TITLE
Add an argument that lists available containers

### PR DESCRIPTION
**Pull request by naxoc**

### CODE REVIEW

**Comment by xendk** [comment]
The build failure seems to be a timeout because the tests runs too slow, I'll look into into it.

No tests?

**Comment by xendk** [comment]
Oh, and bump the version in gemfile to 1.1.0.

**Comment by naxoc** [comment]
Added tests, but now it seems that none are run on GH :)

**Comment by xendk** [comment]
OK, that's fixed now. Please remove the version bumping, as I've moved to using tags to trigger publishing instead (the previous way was suboptimal).

**Pull request merged**
